var bauchbindendata = ["pog",
"begeisteter Bauchbindentester.",
"hat schon mal Rick Astley getroffen.",
"Wer das liest ist doff.",
"professioneller Idiotentester.",
"isst im Notfall auch Redstone.",
"hat (fast) jede Landung überlebt.",
"wurde bereits von Gomme gebannt.",
"mag Android ziemlich sehr.",
"begeisterter Apfelesser.",
"Wasserkühlung trotz Angst vor Wasser in der Technik.",
"findet Minekart überflüssig.",
"spendet, damit Erdmännchen nicht gegrillt werden.",
"der König im RickRollen.",
"Redstonekanal und trotzdem keinen Plan von Technik.",
"glaubt noch an Heilsteine.",
"ein Mann wie aus dem Bilderbuch.",
"war schon seit 3 Tagen nicht mehr beim Arbeitsamt.",
"trinkt zu viel Alkohol.",
"setzt sich für die Rechte von Fruchtfliegen ein.",
"weiß als einziger was mit Carsten los ist.",
"hat zu viel Schokolade bei sich rumliegen.",
"wäre gerne Astronaut geworden.",
"war seit 3 Jahren nicht mehr im Zoo.",
"hat bereits 395 verschiedene Hoster getestet.",
"hat von Kai ein Eis bekommen.",
"erstellt 90% der TJC-Memes.",
"wurde seit 4 Tagen nicht mehr gefüttert.",
"1# '1000 Wege ins Gras zu beißen'-Kandidat",
"kommt gut mit seiner Streamorganisation zurecht",
"never gonna give him up",
"Mathe-Student - 'Was war nochmal 3+4? 8?'",
"hat 'keine' Angst vor Gewitter",
"hat ein neues Mischpult - Poppy?",
"hat eine Phobie vor Minecraft-Gemälden.",
"Hier könnte ihre Werbung stehen.",
"hat Hunger auf Pizza.",
"besucht in seiner Freizeit gerne discord.gg/thejocraft",
"spielt gerne mit Bauklötzen.",
"hat es hinbekommen, eine McDonalds-Bestellung ohne Rückfrage abzugeben.",
"findet manchmal sogar Talk #42.",
"leakt alles was leakbar ist.",
"hat heute seine Nikotinspritze vergessen.",
"Lorem ipsum dolor sit amet, consectetur adipisici elit, …",
"eigentlich schon lange 35.",
"Doitsch-Schtudänd",
"braucht dringend neue Anime-Empfehlungen.",
"hat gerade sein Alter geleaked."]
